### ISSUE TITLE
Example for alexa definition

### ISSUE THREAD

**Issue by sidey79** [fhem/alexa-fhem-docker#4]
I haven't found any examples how to configure the Alexa definition inside Fhem to work with this container.

Can you provide some?
I think i need the alexa module to get the needed registration key.

**Comment by jpawlowski** [comment]
I think this dedicated container doesn't work well anymore when using the latest and greatest FHEM alexa module because the new module is no longer designed to really work with dedicated instances (even though the maintainer says it should, but also states it's not tested as far as I remember).

I personally had used alexa as part of the actual FHEM container which works pretty will. In fact, there is no real reason or benefit anymore to keep alexa-fhem in a dedicated container (besides your ego, of course ;-)).

**Comment by sidey79** [comment]
Oh, i choosed the dedicated container, because it belongs to another sexurity boundary in my opinion.

**Comment by jpawlowski** [comment]
sex what?!? :D
Anyway, as I was saying, there is no gain in security if you do not plan to use custom skills but simply the FHEM Home Automation skills. Connectivity is outbound only.

**Comment by sidey79** [comment]
I understand your point of view.
My understanding crrently is, that the echo device is sending speech to aws. AWS will hand over to the fhem e.V. server. The fhem e.V. server gives that information to the alexa-fhem node js deamon.

After all i know, the alexa-fhem deamon seems to get it commands from the Fhem e.V.  server. So the alexa-fhem and Fhem e.V. server should not have access to my Server or container which runs FHEM, because this system hast access to serval internal systems.

I`ll try to get this working.

**Comment by jpawlowski** [comment]
Maybe worth doing a real-world risk analysis - my needle's banging pretty low here ... = not worth the effort in my opinion. I'd rather go for simplicity and put more effort into functionality. 🤷🏼‍♂️

**Comment by sidey79** [comment]
Just to celarify some things.

The container works pretty good. It can communicate with fhem on the host or any other location. 

There is only one thing which is critical during setup. Before starting the container, the connection to fhem needs to be configured properly so that it can connect to the alexa fhem device and configure anything.

I need to do a "reset" command to get this working, because at my first start the communication to fhem was not possible.
